import type {
  CurrentEvent,
  DailyUpdate,
  GameCharacter,
  InventoryItem,
} from "@/features/game/types";

export const mockCharacters: GameCharacter[] = [
  {
    id: "minh",
    name: "Minh",
    initials: "MI",
    role: "Trụ cột",
    state: "shelter",
    stats: { health: 78, satiety: 61, hydration: 34, sanity: 72 },
    conditions: [{ label: "Đang khát", tone: "warning" }],
  },
  {
    id: "lan",
    name: "Lan",
    initials: "LA",
    role: "Y tế",
    state: "shelter",
    stats: { health: 48, satiety: 53, hydration: 67, sanity: 58 },
    conditions: [
      { label: "Bị thương", tone: "danger" },
      { label: "Cần nghỉ ngơi", tone: "neutral" },
    ],
  },
  {
    id: "hung",
    name: "Hùng",
    initials: "HU",
    role: "Thám hiểm",
    state: "expedition",
    stats: { health: 85, satiety: 70, hydration: 62, sanity: 66 },
    conditions: [],
    expeditionDay: 3,
  },
  {
    id: "an",
    name: "An",
    initials: "AN",
    role: "Kỹ thuật",
    state: "shelter",
    stats: { health: 69, satiety: 42, hydration: 55, sanity: 39 },
    conditions: [{ label: "Lo âu", tone: "warning" }],
  },
];

export const mockInventory: InventoryItem[] = [
  {
    id: "canned-food-intact",
    key: "canned_food",
    name: "Đồ hộp",
    shortName: "Đồ hộp",
    description: "Một khẩu phần được bảo quản kỹ. Không ngon, nhưng đủ sống.",
    category: "food",
    condition: "intact",
    quantity: 3,
    icon: "can",
    usable: true,
  },
  {
    id: "water-intact",
    key: "water",
    name: "Nước sạch",
    shortName: "Nước",
    description: "Nước uống còn sạch, mỗi đơn vị đủ cho một lần sử dụng.",
    category: "water",
    condition: "intact",
    quantity: 4,
    icon: "water",
    usable: true,
  },
  {
    id: "medicine-intact",
    key: "medicine",
    name: "Thuốc",
    shortName: "Thuốc",
    description: "Thuốc tổng hợp dùng để điều trị bệnh và nhiễm trùng nhẹ.",
    category: "medical",
    condition: "intact",
    quantity: 1,
    icon: "medicine",
    usable: true,
  },
  {
    id: "bandage-intact",
    key: "bandage",
    name: "Băng cứu thương",
    shortName: "Băng gạc",
    description: "Dùng để sơ cứu vết thương và ngăn tình trạng xấu đi.",
    category: "medical",
    condition: "intact",
    quantity: 2,
    icon: "bandage",
    usable: true,
  },
  {
    id: "radio-intact",
    key: "radio",
    name: "Radio",
    shortName: "Radio",
    description: "Có thể bắt tín hiệu yếu từ bên ngoài nếu thời tiết thuận lợi.",
    category: "tool",
    condition: "intact",
    quantity: 1,
    icon: "radio",
    usable: false,
  },
  {
    id: "flashlight-intact",
    key: "flashlight",
    name: "Đèn pin",
    shortName: "Đèn pin",
    description: "Nguồn sáng đáng tin cậy cho những chuyến đi xa.",
    category: "tool",
    condition: "intact",
    quantity: 1,
    icon: "flashlight",
    usable: false,
  },
  {
    id: "axe-broken",
    key: "axe",
    name: "Rìu bị hỏng",
    shortName: "Rìu",
    description: "Lưỡi rìu đã lỏng. Cần sửa trước khi có thể sử dụng an toàn.",
    category: "tool",
    condition: "broken",
    quantity: 1,
    icon: "axe",
    usable: false,
  },
  {
    id: "map-intact",
    key: "old_map",
    name: "Bản đồ cũ",
    shortName: "Bản đồ",
    description: "Một vài địa điểm bên ngoài đã được đánh dấu bằng mực đỏ.",
    category: "quest",
    condition: "intact",
    quantity: 1,
    icon: "map",
    usable: false,
  },
];

export const mockDailyUpdates: DailyUpdate[] = [
  {
    id: "lan-thirst",
    type: "warning",
    title: "Lan cần được chăm sóc",
    description: "Vết thương chưa ổn định. Nếu không xử lý, sức khỏe sẽ tiếp tục giảm.",
    time: "Sáng nay",
  },
  {
    id: "expedition-signal",
    type: "success",
    title: "Nhận được tín hiệu của Hùng",
    description: "Hùng vẫn an toàn sau ba ngày bên ngoài và đang tiếp tục tìm kiếm vật tư.",
    time: "2 giờ trước",
  },
  {
    id: "night-noise",
    type: "neutral",
    title: "Có tiếng động ngoài cửa hầm",
    description: "Tiếng kim loại va vào nhau xuất hiện nhiều lần trong đêm.",
    time: "Đêm qua",
  },
];

export const mockCurrentEvent: CurrentEvent = {
  id: "mysterious-knock",
  title: "Tiếng gõ cửa",
  description:
    "Ba tiếng gõ ngắn vang lên từ phía bên kia cánh cửa. Một giọng nói khàn đặc xin đổi thông tin về khu cứu trợ lấy một chai nước sạch.",
  category: "Gặp gỡ",
  rarity: "rare",
  choices: [
    {
      id: "trade-water",
      label: "Đổi một chai nước",
      description: "Mất 1 nước sạch và nghe thông tin của người lạ.",
      requiredItemKey: "water",
      requiredQuantity: 1,
      variant: "primary",
    },
    {
      id: "ignore",
      label: "Giữ im lặng",
      description: "Không tiêu hao tài nguyên, nhưng người lạ có thể không quay lại.",
      variant: "secondary",
    },
  ],
};
